server {
    listen 80;

    # El ALB maneja el routing a los backends via path-based rules.
    # Nginx solo sirve los archivos estáticos del build de React.
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
