server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
<<<<<<< Updated upstream
        proxy_pass http://172.31.35.112:8081/;
=======
        proxy_pass http://172.31.35.112:8081/api/;
>>>>>>> Stashed changes
        proxy_set_header Host $host;
    }
}
